"""Typed repository facade: one import for every store operation.

Implementation lives in :mod:`repo_inventory`, :mod:`repo_billing` and :mod:`repo_sync`.
"""

from __future__ import annotations

from insights.store.repo_billing import (
    INSTANCE_SCOPES,
    Money,
    UsageRow,
    billing_meta,
    credits_per_instance,
    last_synced_day,
    list_payg,
    list_prepaid,
    query_usage,
    replace_credit_usage,
    replace_prepaid,
    upsert_payg,
    usage_by_category,
    usage_by_instance,
    usage_by_period,
    usage_total,
    with_percent,
)
from insights.store.repo_inventory import (
    AnalyticsClusterRow,
    AppServiceRow,
    ClusterRow,
    count_inventory,
    get_analytics_cluster,
    get_app_service,
    get_app_service_for_cluster,
    get_cluster,
    get_organization,
    instance_names,
    list_analytics_clusters,
    list_app_endpoints,
    list_app_services,
    list_buckets,
    list_clusters,
    list_projects_with_counts,
    prune_analytics_clusters,
    prune_app_services,
    prune_clusters,
    prune_projects,
    replace_app_endpoints,
    replace_buckets,
    upsert_analytics_clusters,
    upsert_app_services,
    upsert_clusters,
    upsert_organization,
    upsert_projects,
)
from insights.store.repo_sync import (
    SyncRunRow,
    create_sync_run,
    empty_detail,
    finish_sync_run,
    last_sync_run,
    list_sync_runs,
    mark_stale_runs_failed,
)

__all__ = [
    "INSTANCE_SCOPES",
    "AnalyticsClusterRow",
    "AppServiceRow",
    "ClusterRow",
    "Money",
    "SyncRunRow",
    "UsageRow",
    "billing_meta",
    "count_inventory",
    "create_sync_run",
    "credits_per_instance",
    "empty_detail",
    "finish_sync_run",
    "get_analytics_cluster",
    "get_app_service",
    "get_app_service_for_cluster",
    "get_cluster",
    "get_organization",
    "instance_names",
    "last_sync_run",
    "last_synced_day",
    "list_analytics_clusters",
    "list_app_endpoints",
    "list_app_services",
    "list_buckets",
    "list_clusters",
    "list_payg",
    "list_prepaid",
    "list_projects_with_counts",
    "list_sync_runs",
    "mark_stale_runs_failed",
    "prune_analytics_clusters",
    "prune_app_services",
    "prune_clusters",
    "prune_projects",
    "query_usage",
    "replace_app_endpoints",
    "replace_buckets",
    "replace_credit_usage",
    "replace_prepaid",
    "upsert_analytics_clusters",
    "upsert_app_services",
    "upsert_clusters",
    "upsert_organization",
    "upsert_payg",
    "upsert_projects",
    "usage_by_category",
    "usage_by_instance",
    "usage_by_period",
    "usage_total",
    "with_percent",
]
